version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379"
    volumes:
      - 'redis:/var/lib/redis/data'

  app:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/12
    command: ./entrypoints/docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on: 
      - redis
      - postgres
    volumes:
      - .:/app
      - gems:/gems
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    tty: true
    stdin_open: true

  sidekiq:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/12
    depends_on:
      - app      
      - postgres
      - redis
    volumes:
      - .:/app
      - gems:/gems
    command: ./entrypoints/sidekiq-entrypoint.sh


volumes:
  postgres:
  redis:
  gems:
